Repository wecode-bootcamp-korea/35-2nd-SeSac-frontend, pull requests merged in 2022-08, with the labels that each got.

#2 [35기 박성은 feature/Login]
  .gitignore
  package-lock.json
  public/index.html
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Styled.Login.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청, 수정완료

#4 [35기 손민지] Add: 상세 페이지 - 댓글/게시글 기능 구현 완료 및 API 활용한 지도 구현 완료
  public/data/commentList.json
  public/data/post.json
  public/images/SeSAC.png
  public/images/SesacSesac.jpg
  public/images/kakao.png
  public/index.html
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Styled.Nav.js
  src/fonts/OneMobilePop.otf
  src/fonts/fonts.js
  src/pages/Detail/Comment.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Styled.Detail.js
  src/pages/Login/Login.js
  src/pages/Login/Styled.Login.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#3 [35기 김영수 feature/Post Form 기능 구현 및 통신 완료(의존성배열이 사이더에 걸립니다..)
  package-lock.json
  package.json
  public/images/Post/people.jpg
  public/images/Post/upload.png
  public/index.html
  src/index.js
  src/pages/Post/Post.js
  src/pages/Post/Styled.Post.js
Labels: 멘토 리뷰 요청, 수정완료

#6 [35기 박성은]Fix: nav수정, footer 추가, login 수정
  public/images/loginImg/SesacSesac.jpg
  public/images/loginImg/kakao.png
  public/images/navImg/writing.png
  public/index.html
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Styled.Footer.js
  src/components/Nav/Nav.js
  src/components/Nav/Styled.Nav.js
  src/pages/Login/Login.js
  src/pages/Main/MainBtn/Styled.MainBtn.js
  src/pages/Main/Slider/Styled.SimpleSlider.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#1 [35기 이금관] Feature/list 검색/필터기능 구현, 지도 작업중, 통신 거의 구현
  package-lock.json
  package.json
  public/data/Data.js
  public/data/Recommend.json
  public/data/StoryData.json
  public/images/img1.png
  public/images/img2.png
  public/images/img3.png
  public/index.html
  src/pages/List/CategoryList.js
  src/pages/List/KakaoMap.js
  src/pages/List/List.js
  src/pages/List/RecommendList.js
  src/pages/List/StoryList.js
  src/pages/List/Styeld.StoryList.js
  src/pages/List/Styled.List.js
  src/pages/List/Styled.RecommendList.js
Labels: 멘토 리뷰 요청
